name: "YouTrack Move"
description: "Move cards between YouTrack board columns"
inputs:
  github-token:
    description: "GitHub Token"
    required: true
  yt-project-id:
    description: "Issue ID prefix used in the projects"
    required: true
  yt-url:
    description: "Base URL of your YouTrack instance"
    required: true
    default: "https://my-yt.myjetbrains.com/youtrack"
  yt-token:
    description: "Youtrack permanent token"
    required: true
  yt-column-field:
    description: "Youtrack column name type"
    default: "Stage"
  yt-column-triggers:
    description: "Youtrack column names that trigger the action"
    default: "PR Open"
  yt-column-target:
    description: "Youtrack column name to move issues"
    default: "PreProd"
branding:
  icon: "move"
  color: "gray-dark"
runs:
  using: "node12"
  main: "dist/index.js"
